// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: Models.proto

package services

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 来个枚举类型的 商品地域
type ProductAreas int32

const (
	ProductAreas_BEIJING   ProductAreas = 0 //必须从0开始
	ProductAreas_SHANGHAI  ProductAreas = 1
	ProductAreas_SHANGDONG ProductAreas = 2
	ProductAreas_SICHUAN   ProductAreas = 3
	ProductAreas_HEBEI     ProductAreas = 4
	ProductAreas_TIANJING  ProductAreas = 5
)

// Enum value maps for ProductAreas.
var (
	ProductAreas_name = map[int32]string{
		0: "BEIJING",
		1: "SHANGHAI",
		2: "SHANGDONG",
		3: "SICHUAN",
		4: "HEBEI",
		5: "TIANJING",
	}
	ProductAreas_value = map[string]int32{
		"BEIJING":   0,
		"SHANGHAI":  1,
		"SHANGDONG": 2,
		"SICHUAN":   3,
		"HEBEI":     4,
		"TIANJING":  5,
	}
)

func (x ProductAreas) Enum() *ProductAreas {
	p := new(ProductAreas)
	*p = x
	return p
}

func (x ProductAreas) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductAreas) Descriptor() protoreflect.EnumDescriptor {
	return file_Models_proto_enumTypes[0].Descriptor()
}

func (ProductAreas) Type() protoreflect.EnumType {
	return &file_Models_proto_enumTypes[0]
}

func (x ProductAreas) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductAreas.Descriptor instead.
func (ProductAreas) EnumDescriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{0}
}

// 商品详情
type ProductInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProId   int32  `protobuf:"varint,1,opt,name=pro_id,json=proId,proto3" json:"pro_id,omitempty"`      // 商品id
	ProName string `protobuf:"bytes,2,opt,name=pro_name,json=proName,proto3" json:"pro_name,omitempty"` // 商品名称
	// 数组类型的.
	ProTag   []string `protobuf:"bytes,3,rep,name=pro_tag,json=proTag,proto3" json:"pro_tag,omitempty"`         // 商品标签
	ProPrice float32  `protobuf:"fixed32,4,opt,name=pro_price,json=proPrice,proto3" json:"pro_price,omitempty"` // 商品价格
	ProUrl   string   `protobuf:"bytes,5,opt,name=pro_url,json=proUrl,proto3" json:"pro_url,omitempty"`         // 商品链接
	// 枚举类型的
	ProArea ProductAreas `protobuf:"varint,6,opt,name=pro_area,json=proArea,proto3,enum=services.ProductAreas" json:"pro_area,omitempty"` // 商品地域
	// 日期类型的
	ProTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=pro_time,json=proTime,proto3" json:"pro_time,omitempty"` // 上市时间
	// 库存
	ProStockStatus int32 `protobuf:"varint,8,opt,name=pro_stock_status,json=proStockStatus,proto3" json:"pro_stock_status,omitempty"`
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfo) GetProId() int32 {
	if x != nil {
		return x.ProId
	}
	return 0
}

func (x *ProductInfo) GetProName() string {
	if x != nil {
		return x.ProName
	}
	return ""
}

func (x *ProductInfo) GetProTag() []string {
	if x != nil {
		return x.ProTag
	}
	return nil
}

func (x *ProductInfo) GetProPrice() float32 {
	if x != nil {
		return x.ProPrice
	}
	return 0
}

func (x *ProductInfo) GetProUrl() string {
	if x != nil {
		return x.ProUrl
	}
	return ""
}

func (x *ProductInfo) GetProArea() ProductAreas {
	if x != nil {
		return x.ProArea
	}
	return ProductAreas_BEIJING
}

func (x *ProductInfo) GetProTime() *timestamp.Timestamp {
	if x != nil {
		return x.ProTime
	}
	return nil
}

func (x *ProductInfo) GetProStockStatus() int32 {
	if x != nil {
		return x.ProStockStatus
	}
	return 0
}

// 主订单信息
type OrderMain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId int32 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单id
	//int32 pro_id = 2; // 商品id
	OrderNo   string               `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"` // 订单号
	UserId    int32                `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`   // 用户id,加个校验必须大于1000
	OrderTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	// 嵌套 模型
	OrderDetails []*OrderDetail `protobuf:"bytes,6,rep,name=order_details,json=orderDetails,proto3" json:"order_details,omitempty"`
}

func (x *OrderMain) Reset() {
	*x = OrderMain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMain) ProtoMessage() {}

func (x *OrderMain) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMain.ProtoReflect.Descriptor instead.
func (*OrderMain) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{1}
}

func (x *OrderMain) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderMain) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderMain) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderMain) GetOrderTime() *timestamp.Timestamp {
	if x != nil {
		return x.OrderTime
	}
	return nil
}

func (x *OrderMain) GetOrderDetails() []*OrderDetail {
	if x != nil {
		return x.OrderDetails
	}
	return nil
}

// 子订单
type OrderDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DetailId int32   `protobuf:"varint,1,opt,name=detail_id,json=detailId,proto3" json:"detail_id,omitempty"`
	OrderNo  string  `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	ProId    int32   `protobuf:"varint,3,opt,name=pro_id,json=proId,proto3" json:"pro_id,omitempty"`
	ProPrice float32 `protobuf:"fixed32,4,opt,name=pro_price,json=proPrice,proto3" json:"pro_price,omitempty"`
	ProNunm  int32   `protobuf:"varint,5,opt,name=pro_nunm,json=proNunm,proto3" json:"pro_nunm,omitempty"`
}

func (x *OrderDetail) Reset() {
	*x = OrderDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetail) ProtoMessage() {}

func (x *OrderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetail.ProtoReflect.Descriptor instead.
func (*OrderDetail) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDetail) GetDetailId() int32 {
	if x != nil {
		return x.DetailId
	}
	return 0
}

func (x *OrderDetail) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderDetail) GetProId() int32 {
	if x != nil {
		return x.ProId
	}
	return 0
}

func (x *OrderDetail) GetProPrice() float32 {
	if x != nil {
		return x.ProPrice
	}
	return 0
}

func (x *OrderDetail) GetProNunm() int32 {
	if x != nil {
		return x.ProNunm
	}
	return 0
}

// 流模式入门，用户模型
type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserScore int32 `protobuf:"varint,2,opt,name=user_score,json=userScore,proto3" json:"user_score,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserScore() int32 {
	if x != nil {
		return x.UserScore
	}
	return 0
}

var File_Models_proto protoreflect.FileDescriptor

var file_Models_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x02, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70,
	0x72, 0x6f, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72,
	0x6f, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x5f, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x73, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x41, 0x72, 0x65, 0x61, 0x12, 0x35, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x5f, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x70, 0x72, 0x6f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xdb,
	0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x12, 0x21, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x1a, 0x03, 0x20, 0xe8, 0x07, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x3a, 0x0a, 0x0d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x94, 0x01, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x5f,
	0x6e, 0x75, 0x6e, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x4e,
	0x75, 0x6e, 0x6d, 0x22, 0x42, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x2a, 0x5e, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x41, 0x72, 0x65, 0x61, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x45, 0x49, 0x4a, 0x49,
	0x4e, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x48, 0x41, 0x4e, 0x47, 0x48, 0x41, 0x49,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x4e, 0x47, 0x44, 0x4f, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x49, 0x43, 0x48, 0x55, 0x41, 0x4e, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x48, 0x45, 0x42, 0x45, 0x49, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x49, 0x41,
	0x4e, 0x4a, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Models_proto_rawDescOnce sync.Once
	file_Models_proto_rawDescData = file_Models_proto_rawDesc
)

func file_Models_proto_rawDescGZIP() []byte {
	file_Models_proto_rawDescOnce.Do(func() {
		file_Models_proto_rawDescData = protoimpl.X.CompressGZIP(file_Models_proto_rawDescData)
	})
	return file_Models_proto_rawDescData
}

var file_Models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_Models_proto_goTypes = []interface{}{
	(ProductAreas)(0),           // 0: services.ProductAreas
	(*ProductInfo)(nil),         // 1: services.ProductInfo
	(*OrderMain)(nil),           // 2: services.OrderMain
	(*OrderDetail)(nil),         // 3: services.OrderDetail
	(*UserInfo)(nil),            // 4: services.UserInfo
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_Models_proto_depIdxs = []int32{
	0, // 0: services.ProductInfo.pro_area:type_name -> services.ProductAreas
	5, // 1: services.ProductInfo.pro_time:type_name -> google.protobuf.Timestamp
	5, // 2: services.OrderMain.order_time:type_name -> google.protobuf.Timestamp
	3, // 3: services.OrderMain.order_details:type_name -> services.OrderDetail
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Models_proto_init() }
func file_Models_proto_init() {
	if File_Models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Models_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Models_proto_goTypes,
		DependencyIndexes: file_Models_proto_depIdxs,
		EnumInfos:         file_Models_proto_enumTypes,
		MessageInfos:      file_Models_proto_msgTypes,
	}.Build()
	File_Models_proto = out.File
	file_Models_proto_rawDesc = nil
	file_Models_proto_goTypes = nil
	file_Models_proto_depIdxs = nil
}
