// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: Models.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 枚举类型,商品所在区域a,b,c 三个区域
// 枚举类型的值必须要影射为数值类型，并且第一个必须为零，代表默认值
type ProductAreas int32

const (
	ProductAreas_BEI_JING  ProductAreas = 0 //
	ProductAreas_HE_BEI    ProductAreas = 1
	ProductAreas_SHANG_HAI ProductAreas = 2
	ProductAreas_SI_CHUANG ProductAreas = 3
	ProductAreas_WU_HANG   ProductAreas = 4
	ProductAreas_SHAN_DONG ProductAreas = 6
)

// Enum value maps for ProductAreas.
var (
	ProductAreas_name = map[int32]string{
		0: "BEI_JING",
		1: "HE_BEI",
		2: "SHANG_HAI",
		3: "SI_CHUANG",
		4: "WU_HANG",
		6: "SHAN_DONG",
	}
	ProductAreas_value = map[string]int32{
		"BEI_JING":  0,
		"HE_BEI":    1,
		"SHANG_HAI": 2,
		"SI_CHUANG": 3,
		"WU_HANG":   4,
		"SHAN_DONG": 6,
	}
)

func (x ProductAreas) Enum() *ProductAreas {
	p := new(ProductAreas)
	*p = x
	return p
}

func (x ProductAreas) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductAreas) Descriptor() protoreflect.EnumDescriptor {
	return file_Models_proto_enumTypes[0].Descriptor()
}

func (ProductAreas) Type() protoreflect.EnumType {
	return &file_Models_proto_enumTypes[0]
}

func (x ProductAreas) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductAreas.Descriptor instead.
func (ProductAreas) EnumDescriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{0}
}

type ProductModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProId    int32        `protobuf:"varint,1,opt,name=pro_id,json=proId,proto3" json:"pro_id,omitempty"`
	ProName  string       `protobuf:"bytes,2,opt,name=pro_name,json=proName,proto3" json:"pro_name,omitempty"`
	ProPrice float32      `protobuf:"fixed32,3,opt,name=pro_price,json=proPrice,proto3" json:"pro_price,omitempty"`
	ProArea  ProductAreas `protobuf:"varint,5,opt,name=pro_area,json=proArea,proto3,enum=services.ProductAreas" json:"pro_area,omitempty"`
}

func (x *ProductModel) Reset() {
	*x = ProductModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductModel) ProtoMessage() {}

func (x *ProductModel) ProtoReflect() protoreflect.Message {
	mi := &file_Models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductModel.ProtoReflect.Descriptor instead.
func (*ProductModel) Descriptor() ([]byte, []int) {
	return file_Models_proto_rawDescGZIP(), []int{0}
}

func (x *ProductModel) GetProId() int32 {
	if x != nil {
		return x.ProId
	}
	return 0
}

func (x *ProductModel) GetProName() string {
	if x != nil {
		return x.ProName
	}
	return ""
}

func (x *ProductModel) GetProPrice() float32 {
	if x != nil {
		return x.ProPrice
	}
	return 0
}

func (x *ProductModel) GetProArea() ProductAreas {
	if x != nil {
		return x.ProArea
	}
	return ProductAreas_BEI_JING
}

var File_Models_proto protoreflect.FileDescriptor

var file_Models_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x72, 0x6f,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x72, 0x6f, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x5f,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x73, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x41, 0x72, 0x65, 0x61, 0x2a, 0x62, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x41, 0x72, 0x65, 0x61, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x42,
	0x45, 0x49, 0x5f, 0x4a, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x5f,
	0x42, 0x45, 0x49, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x4e, 0x47, 0x5f, 0x48,
	0x41, 0x49, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x49, 0x5f, 0x43, 0x48, 0x55, 0x41, 0x4e,
	0x47, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x55, 0x5f, 0x48, 0x41, 0x4e, 0x47, 0x10, 0x04,
	0x12, 0x0d, 0x0a, 0x09, 0x53, 0x48, 0x41, 0x4e, 0x5f, 0x44, 0x4f, 0x4e, 0x47, 0x10, 0x06, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Models_proto_rawDescOnce sync.Once
	file_Models_proto_rawDescData = file_Models_proto_rawDesc
)

func file_Models_proto_rawDescGZIP() []byte {
	file_Models_proto_rawDescOnce.Do(func() {
		file_Models_proto_rawDescData = protoimpl.X.CompressGZIP(file_Models_proto_rawDescData)
	})
	return file_Models_proto_rawDescData
}

var file_Models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Models_proto_goTypes = []interface{}{
	(ProductAreas)(0),    // 0: services.ProductAreas
	(*ProductModel)(nil), // 1: services.ProductModel
}
var file_Models_proto_depIdxs = []int32{
	0, // 0: services.ProductModel.pro_area:type_name -> services.ProductAreas
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Models_proto_init() }
func file_Models_proto_init() {
	if File_Models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Models_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Models_proto_goTypes,
		DependencyIndexes: file_Models_proto_depIdxs,
		EnumInfos:         file_Models_proto_enumTypes,
		MessageInfos:      file_Models_proto_msgTypes,
	}.Build()
	File_Models_proto = out.File
	file_Models_proto_rawDesc = nil
	file_Models_proto_goTypes = nil
	file_Models_proto_depIdxs = nil
}
